// FILTER
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND'
// FAVOURITES
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
// CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';
export const APPLY_DISCOUNT = 'APPLY_DISCOUNT';